name: CICD with gitAction ArgoCD ECR EKS

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update DB Info
        run: |
          sed -i "s|DB_HOST|'${{ secrets.DB_HOST }}'|g" index.js
          sed -i "s|DB_USER|'${{ secrets.DB_USER }}'|g" index.js
          sed -i "s|DB_PASSWORD|'${{ secrets.DB_PASSWORD }}'|g" index.js
          sed -i "s|DB_DATABASE|'${{ secrets.DB_DATABASE }}'|g" index.js


      - name: Get image tag(verion)
        id: image-version
        run: |
          VERSION=$(echo ${{ github.sha }})
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.AWS_REGISTRY_URL }}:${{ github.sha }}

      - name: Cleanup
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ secrets.AWS_REGISTRY_URL }}:${{ github.sha }}


# image만 테스트
#   Deploy:
#     needs: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup Kustomize
#         uses: imranismail/setup-kustomize@v1

#       - name: Checkout kustomize repository
#         uses: actions/checkout@v2
#         with:
#           repository: majjangjjang/bank_system_yaml
#           ref: master
#           token: ${{ secrets.ACTION_TOKEN }}
#           path: bank_system_yaml

#       - name: Update Kubernetes resources
#         run: |
#           cd bank_system_yaml/overlays/deploy/
#           kustomize edit set image ${{ secrets.AWS_REGISTRY_URL }}=${{ secrets.AWS_REGISTRY_URL }}:${{ github.sha }}
#           cat kustomization.yaml

#       - name: Commit files
#         run: |
#           cd bank_system_yaml
#           git config --global user.email "majjangjjang@github.com"
#           git config --global user.name "majjangjjang"
#           git commit -am "Update image tag"
#           git push -u origin master